// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvpylervaaklqwiafuag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cHlsZXJ2YWFrbHF3aWFmdWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxOTY5OTcsImV4cCI6MjA1MTc3Mjk5N30.I6oBrFrn-qtW9CqE3cdpkwwTWb48yE39pLTas_5Mg14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);